<?php

namespace mttl\gsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptableRepository extends EntityRepository
{
}
