<?php

namespace mttl\gsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends EntityRepository
{
    
    public function getVisiteurComptable($idComptable){
        
        $query = $this->createQueryBuilder('v')
                ->where('v.idcomptable = :idcomptable')
                ->setParameter(':idcomptable', $idComptable);
       
        return $query;
    }
}
